// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFvJHZD5sYyYLgo1EyKuZbXehDlqN3Pdw',
    appId: '1:409615345427:web:9fb3b143dacb25b0d6dce6',
    messagingSenderId: '409615345427',
    projectId: 'ecommerstestmenu',
    authDomain: 'ecommerstestmenu.firebaseapp.com',
    storageBucket: 'ecommerstestmenu.appspot.com',
    measurementId: 'G-SQW0Q13Y4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITTAXr_8YyG9a4S6YBGu9h6TGZm867UU',
    appId: '1:409615345427:android:27006c0e42a636b3d6dce6',
    messagingSenderId: '409615345427',
    projectId: 'ecommerstestmenu',
    storageBucket: 'ecommerstestmenu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbY2sXZH4R2gP7oT2DwjX5zSXbYYYoVB0',
    appId: '1:409615345427:ios:0ab6972f2ab972f6d6dce6',
    messagingSenderId: '409615345427',
    projectId: 'ecommerstestmenu',
    storageBucket: 'ecommerstestmenu.appspot.com',
    iosClientId: '409615345427-df37ncnspjf2p53sbm7tqnk40cvgaigg.apps.googleusercontent.com',
    iosBundleId: 'com.valizadarustam.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbY2sXZH4R2gP7oT2DwjX5zSXbYYYoVB0',
    appId: '1:409615345427:ios:0ab6972f2ab972f6d6dce6',
    messagingSenderId: '409615345427',
    projectId: 'ecommerstestmenu',
    storageBucket: 'ecommerstestmenu.appspot.com',
    iosClientId: '409615345427-df37ncnspjf2p53sbm7tqnk40cvgaigg.apps.googleusercontent.com',
    iosBundleId: 'com.valizadarustam.ecommerceapp',
  );
}
